includes = [".dotter/<system>.toml"]

#[files]

packages = [
    "discord",
    "git",
    "kitty",
    "neovim",
    "starship",
    "sway",
    "swaylock",
    "swaync",
    "tmux",
    "vscode",
    "waybar",
    "zsh",
    #"foot",
]

[variables]
install_pkgs = false
update_pkgs = false
